version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"  # Flask
      - "8000:8000"  # FastAPI
    volumes:
      - ./:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_SECRET_KEY=dev_key_for_ocr_app
      - TESSERACT_CMD=/usr/bin/tesseract
      - TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/tessdata
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 